### ISSUE TITLE
cannot run npm i on the demo project

### ISSUE THREAD

**Issue by mahen23** [capawesome-team/capacitor-nfc-demo#32] opened 2024-10-01 05:54 UTC
Getting below error: 
npm install --legacy-peer-deps
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm error code E401
npm error 401 Unauthorized - GET https://npm.pkg.github.com/download/@capawesome-team/capacitor-nfc/6.0.0/3f8690e9c2b1db3a9785c5f7b0b5d45d9aa8f730 - authentication token not provided
npm error A complete log of this run can be found in: /home/mahen/.npm/_logs/2024-10-01T05_53_49_673Z-debug-0.log

**Comment by robingenz** [comment] 2024-10-01 11:25
Please take a look at our [Common issues](https://capawesome.io/sponsors/insiders/getting-started/#common-issues) section. I close this issue as duplicate of #27.

**Closed as not planned by robingenz** 2024-10-01 11:25 UTC
